# Workflow to test webscraping

name: test_autoscrape

# Trigger on push to test/autoscrape branch or when functions.R is updated
on:
  push:
    branches:
      - 'test/autoscrape'
  push:
    paths:
      - 'R/functions.R'
     

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Scraping job
  autoscrape:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Load repo and install R
    steps:
    - uses: actions/checkout@v2
      with: 
        ref: test/autoscrape
    - uses: r-lib/actions/setup-r@master

    # Set-up R
    - name: Install pacakges
      run: |
        R -e 'install.packages("tidyverse")'
        R -e 'install.packages("pdftools")'
        R -e 'install.packages("countrycode")'
        
    # Run R script
    - name: Scrape
      run: Rscript get_all_data.R
    
    # Save artifacts
    - name: Upload data
      uses: actions/upload-artifact@v1.0.0
      with:
        name: autoscrape_test_data
        path: data/

    - name: Upload log
      uses: actions/upload-artifact@v1.0.0
      with:
        name: autoscrape_test_log
        path: processing.log
